### ISSUE TITLE
need help with an issue: open the .py file with python3.11 on windows 11 and enters the book code: yvhah/vzyg. the terminal just shut down

### ISSUE THREAD

**Issue by tpJaime** [EngrMoazDev/fliphtml5Downloader#2]
need help with an issue: open the .py file with python3.11 on windows 11 and enters the book code: yvhah/vzyg. the terminal just shut down

**Comment by EngrMoazDev** [comment]
Since you closed the issue, so I am assuming that you were able to sort out what was the problem on your end.
